#ifndef VENUS_PROJECT_CONFIG_HPP
#define VENUS_PROJECT_CONFIG_HPP

#define CORE_CPU_CALIBRATION_CYCLES_COUNT 10000
#define DEFAULT_ITERATIONS_COUNT 10000
#define DEFAULT_ITERATIONS_SKIP  100

#endif //VENUS_PROJECT_CONFIG_HPP
